<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <ApplicationIcon>Scroll.ico</ApplicationIcon>
    <NoWin32Manifest>true</NoWin32Manifest>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
	<GenerateResourceWarnOnBinaryFormatterUse>false</GenerateResourceWarnOnBinaryFormatterUse>
    <NoWarn>$(NoWarn);SYSLIB0011</NoWarn>
    <AssemblyVersion>13.0.1.0</AssemblyVersion>
    <Copyright>Copyright © 2021 - 2025 - Habitual Indolence / Gamers' Syndicate - All rights reserved. This product is protected by copyright and distributed under licences restricting copying, distribution and decompilation.</Copyright>
    <FileVersion>13.0.1.0</FileVersion>
    <Title>Masterplan</Title>
    <RunPostBuildEvent>Always</RunPostBuildEvent>
    <Version>13.0.1.0</Version>
    <Product>Masterplan Adventure Design Studio</Product>
    <Description>A Dungeons &amp; Dragons 4e Adventure Design Tool</Description>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <Optimize>false</Optimize>
    <DocumentationFile>bin\Release\Masterplan.XML</DocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Update="Controls\BreakdownPanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\CalendarPanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\CardDeck.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\DefaultTextBox.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Controls\DicePanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\FilterPanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\InfoPanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\InitiativePanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\KeyAbilitiesPanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\DeckGrid.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\DemographicsPanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\DiceGraphPanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\EncounterGauge.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\Elements\EncounterPanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\HitPointGauge.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\LevelRangePanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\LibraryHelpPanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\Elements\MapElementPanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\MapView.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\PlotView.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\QuestPanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\Elements\RegionalMapPanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\Elements\SkillChallengePanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\TilePanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\TokenPanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\TitlePanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\Elements\TrapElementPanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\WelcomePanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Wizards\MapSizePage.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Wizards\MapTypePage.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Wizards\EncounterSelectionPage.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Wizards\EncounterTemplatePage.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Wizards\MapAreasPage.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Wizards\MapLibrariesPage.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Wizards\VariantFinishPage.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Wizards\VariantBasePage.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Wizards\VariantRolePage.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Wizards\VariantTemplatesPage.cs">
      <SubType>UserControl</SubType>
    </Compile>
  </ItemGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <Optimize>false</Optimize>
    <DocumentationFile>bin\Release\Masterplan.XML</DocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Scroll.ico" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Controls\LevelRangePanel.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Controls\LevelRangePanel.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Controls\LevelRangePanel.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Controls\LevelRangePanel.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Controls\InfoPanel.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Controls\InfoPanel.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Controls\InfoPanel.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Controls\InfoPanel.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Controls\FilterPanel.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Controls\FilterPanel.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Controls\FilterPanel.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Controls\FilterPanel.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Controls\DicePanel.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>"Controls\DicePanel.resx"</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Controls\DicePanel.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>"Controls\DicePanel.Designer.cs"</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Controls\EncounterGauge.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Controls\EncounterGauge.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Controls\EncounterGauge.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Controls\EncounterGauge.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Resources1.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources1.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="UI\PlayerOptions\OptionWeaponForm.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>UI\PlayerOptions\OptionWeaponForm.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="UI\PlayerOptions\OptionWeaponForm.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>UI\PlayerOptions\OptionWeaponForm.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="PuppeteerSharp" Version="20.2.4" />
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="REM 1. Copy Manual.pdf only if it exists&#xA;if exist &quot;$(ProjectDir)..\Manual.pdf&quot; xcopy /y &quot;$(ProjectDir)..\Manual.pdf&quot; &quot;$(TargetDir)&quot;&#xA;&#xA;REM 2. Create Libraries folder if it does NOT exist (using &quot;if not exist&quot;)&#xA;if not exist &quot;$(TargetDir)Libraries&quot; md &quot;$(TargetDir)Libraries&quot;&#xA;&#xA;REM 3. Copy .library files only if the source directory exists&#xA;if exist &quot;$(ProjectDir)..\Libraries\&quot; xcopy /y &quot;$(ProjectDir)..\Libraries\*.library&quot; &quot;$(TargetDir)Libraries\&quot;" />
  </Target>
</Project>